language: node_js
node_js:
- stable
services:
- mysql
before_install:
- openssl aes-256-cbc -K $encrypted_0d75de8bf757_key -iv $encrypted_0d75de8bf757_iv
  -in regal-creek-290403-cdcacdf85698.json.enc -out regal-creek-290403-cdcacdf85698.json
  -d
- mysql -e 'CREATE DATABASE cs3219TaskB;'
- mysql -e 'USE cs3219TaskB; CREATE TABLE IF NOT EXISTS users ( username VARCHAR(255)
  PRIMARY KEY, password VARCHAR(255), firstname VARCHAR(255),lastname VARCHAR(255),
  mobile INTEGER);'
cache:
  directories:
  - node_modules

before_deploy:
  - git restore .
deploy:
  provider: gae
  keyfile: regal-creek-290403-cdcacdf85698.json
  project: regal-creek-290403
