language: node_js
node_js:
- stable
services:
- mysql
before_install:
- mysql -e 'CREATE DATABASE cs3219TaskB;'
- mysql -e 'USE cs3219TaskB; CREATE TABLE IF NOT EXISTS users ( username VARCHAR(255)
  PRIMARY KEY, password VARCHAR(255), firstname VARCHAR(255),lastname VARCHAR(255),
  mobile INTEGER);'
cache:
  directories:
  - node_modules
